config/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crypto.urls', namespace='crypto')),
]

if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
    )

crypto/urls.py
from django.urls import path, re_path, include

from crypto import views

app_name = 'crypto'

urlpatterns = [
	path('', views.landing, name='dashboard'),
]

crypto/models.py
from django.contrib import admin
from django.db import models
from django.conf import settings

# Create your models here.
from django.utils import timezone
from forex_python.converter import CurrencyRates, CurrencyCodes, RatesNotAvailableError

from crypto.utils import crypto_image_path

# TODO: Presaving
# img = Image.open(self.image.path)
# if (img.height != img.width):
#     size = min(img.size)
#     left = (img.width - size) // 2
#     top = (img.height - size) // 2
#     right = (img.width + size) // 2
#     bottom = (img.height + size) // 2
#     img = img.crop((left, top, right, bottom))
#
# if (img.height > 200 or img.width > 200):
#     size = (100, 100)
#     img.thumbnail(size)
#
# img.save(self.image.path)


class Crypto(models.Model):
    symbol = models.CharField(max_length=10, help_text='Crypto Ticker used for querying from CoinMarketCap')
    display_name = models.CharField(max_length=64, help_text='Used as the header when charting')
    show_overall = models.BooleanField(default=False, help_text='Show overall value instead of current price')
    show_chart = models.BooleanField(default=False, verbose_name='Chart crypto', help_text='Show 7-day chart with price trend on Dashboard')
    image = models.ImageField(default='crypto/default.png', upload_to=crypto_image_path)
    enabled = models.BooleanField(default=True, help_text='Hides crypto from Dashboard and does not pull further information')
    order = models.PositiveSmallIntegerField(default=999)
    updated = models.DateTimeField(auto_now=True)
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('order', 'symbol')

    def __str__(self):
        return self.symbol

    @property
    def market_valuex(self):
        purchase_amount = sum([p.amount * p.target_price for p in self.purchases.all()])
        market_value = purchase_amount * self.data.all()[:1][0].target_price
        return purchase_amount


class CryptoData(models.Model):
    crypto = models.ForeignKey(Crypto, on_delete=models.CASCADE, related_name='data')
    source_price = models.FloatField()
    source_currency = models.CharField(max_length=4)
    target_price = models.FloatField()
    target_currency = models.CharField(max_length=4)
    percent_day = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='24h Percentual Change')
    rank = models.PositiveIntegerField()
    timestamp = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Price Data'
        verbose_name_plural = 'Price Data'
        get_latest_by = 'timestamp'

    def save(self, *args, **kwargs):
        if not self.target_price:
            # Converts currency to target currency because CoinMarket's integrated conversion sucks
            from crypto.services import currency_convert
            self.target_currency = settings.TARGET_CURRENCY or settings.COINMARKET_CURRENCY
            self.target_price = currency_convert(
                source_currency=self.source_currency,
                target_currency=self.target_currency,
                source_amount=self.source_price
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return f'[{self.crypto}] {self.price}@{self.timestamp}'

    @property
    @admin.display(
        ordering='target_price',
        description='Price',
    )
    def price(self) -> str:
        c = CurrencyCodes()
        symbol = c.get_symbol(self.target_currency)
        return f'{self.target_price:.20f} {symbol}'

    @property
    @admin.display(
        ordering='percent_day',
        description='24h percentual',
    )
    def percent(self) -> str:
        return f'{self.percent_day:+.2f} %'


class CryptoPurchases(models.Model):
    crypto = models.ForeignKey(Crypto, on_delete=models.CASCADE, related_name='purchases')
    amount = models.FloatField()
    buy_price = models.FloatField(
        help_text='If no buy price is specified, it will be looked up on '
                  'CoinMarketCap based on the buying timestamp (requires Advanced API plan)'
    )
    buy_currency = models.CharField(max_length=4)
    target_price = models.FloatField(
        blank=True,
        help_text='Automatically converts buying price into localized-target price if left empty'
    )
    target_currency = models.CharField(
        max_length=4, blank=True,
        help_text='Automatically converty buying price into localized-target price if left empty'
    )
    bought_at = models.DateTimeField(default=timezone.now, blank=True)

    class Meta:
        verbose_name = 'Purchase'

    def save(self, *args, **kwargs):
        if not self.pk and not self.buy_currency:
            self.buy_currency = settings.TARGET_CURRENCY or settings.COINMARKET_CURRENCY

        if not self.target_price:
            from crypto.services import currency_convert
            self.target_currency = settings.TARGET_CURRENCY or settings.COINMARKET_CURRENCY
            self.target_price = currency_convert(
                source_currency=self.buy_currency,
                target_currency=self.target_currency,
                source_amount=self.buy_price,
                timestamp=self.bought_at
            )

        super().save(*args, **kwargs)

    @property
    def total_price(self):
        c = CurrencyCodes()
        symbol = c.get_symbol(self.target_currency)
        return f'{(self.amount*self.target_price):.2f} {symbol}'


class Alert(models.Model):
    crypto = models.ForeignKey(Crypto, on_delete=models.CASCADE)
    price = models.FloatField(help_text='Price of crypto in target currency to surpass')
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Price Alert'

    def __str__(self):
        return f'[{self.crypto}] {self.price}'

crypto/views.py
from django.shortcuts import render
from django.conf import settings

from crypto.models import Crypto
from crypto.selectors import crypto_invest, crypto_ohlc


def landing(request):
    crypto_queryset = Crypto.objects\
        .order_by('order', 'symbol')\
        .prefetch_related('data', 'purchases')\
        .filter(enabled=True)
    cryptos = crypto_invest(
        crypto_queryset=crypto_queryset
    )

    crypto_charts = []
    if not request.GET.get('charts'):
        # ?charts param to disable chart rendering
        crypto_charts = [
            crypto_ohlc(crypto=crypto) for crypto
            in cryptos.filter(show_chart=True)
        ]

    context = {
        'cryptos': cryptos,
        'crypto_charts': crypto_charts
    }
    return render(request, 'crypto/dashboard.html', context)

crypto/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Crypto Tracker</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/favicon.ico" %}">
    <link href="{% static "vendor/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vendor/font-awesome.min.css" %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:400,600,700" rel="stylesheet"/>

    <link href="{% static "styles.css" %}" rel="stylesheet">
  </head>

  <body>
    <div id="wrapper">
      <div class="content-area">
        <div class="container-fluid">
          <div class="main">
            {% block body %}
            {% endblock body %}

            {% block script %}
            {% endblock script %}
          </div>
        </div>
      </div>
    </div>

    <footer id="sticky-footer" class="flex-shrink-0 py-4 text-white-50 mb-2">
      <div class="container text-center text-dark">
        <small>alfonsrv's Crypto Tracker</small>
      </div>
    </footer>

    <script src="{% static "vendor/jquery.slim.min.js" %}"></script>
    <script src="{% static "vendor/apex/apexcharts.js" %}"></script>
    <script src="{% static "scripts.js" %}"></script>
    <script src="{% static "vendor/htmx.min.js" %}"></script>
    {% load django_htmx %}
    {% django_htmx_script %}
  </body>
</html>

crypto/templates/crypto/dashboard.html
{% extends "base.html" %}
{% load static %}
{% load l10n %}
{% load crypto_extras %}

{% block body %}
<div id="crypto"
     hx-get="{% url 'crypto:dashboard' %}"
     hx-trigger="every 150s"
     hx-target="#crypto"
     hx-select="#crypto"
     hx-swap="outerHTML">
  <div class="row mt-2">
    <div class="col-12">
      <small class="float-right mr-1 nowrap">Updated: {% now "SHORT_DATETIME_FORMAT" %}</small>
    </div>
  </div>

  {% for crypto in crypto_charts %}
  <div class="row mt-2 mb-4">
    <div class="col-md-12">
      <div class="box">
        <div id="{{ crypto.symbol }}"></div>
      </div>
    </div>
  </div>
  {% endfor %}

  <div class="row mt-4 mb-4">

  {% for crypto in cryptos %}
    <div class="col-6 col-sm-4 col-md-4 col-lg-3 pb-4">
      <div class="box">
        <div class="crypto d-flex align-items-center ml-sm-2 ml-md-0 {% if forloop.first %}ml-sm-2 ml-md-0{% endif %}">
          <img src="{{ crypto.image.url }}" class="rounded-circle" alt="{{ crypto.display_name }}">
          <div class="d-flex flex-column">
            <span class="price ml-2">
              {% if crypto.show_overall %}
                {{ crypto.market_value|currency_symbol }}
              {% else %}
                {{ crypto.crypto_value|currency_symbol }}<sup>V</sup>
              {% endif %}
            </span>
            <div class="subinfo d-flex">
              <span class="earns {% if crypto.percent_change < 0 %}text-danger{% else %}text-success{% endif %} ml-2">
                {% if crypto.show_overall %}{{ crypto.percent_change|percent }}{% endif %}
              </span>
              <span class="overall {% if crypto.crypto_percent < 0 %}text-danger{% else %}text-success{% endif %} ml-1">
                {{ crypto.crypto_percent|percent }}<sup>24h</sup>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  </div>
</div>
{% endblock body %}



{% block script %}
<script>
function initCharts() {
  {% for crypto in crypto_charts %}
  var options = {
    series: [{
      data: [
        {% for chart in crypto.chart %}
          {
            x: new Date({{ chart.timestampg.timestamp|floatformat }}000),
            y: [
              {{ chart.open|cryptoformat }},
              {{ chart.high|cryptoformat }},
              {{ chart.low|cryptoformat}},
              {{ chart.close|cryptoformat }}
            ]
          },
        {% endfor %}
      ]
    }],
    chart: {
      type: 'candlestick',
      height: 300,
      toolbar: {
        show: false
      },
      animations: {
        enabled: false
      },
    },
    title: {
      text: '{{ crypto.display_name|upper }}',
      align: 'left'
    },
    xaxis: {
      type: 'datetime',
      labels: {
        datetimeUTC: false
      }
    },
    yaxis: {
      tooltip: {
        enabled: true
      }
    },
  };


  var chartBar = new ApexCharts(document.querySelector('#{{ crypto.symbol }}'), options);
  chartBar.render();
  {% endfor %}
}

document.addEventListener("DOMContentLoaded", function(evt) {
  initCharts();
});

document.body.addEventListener('htmx:afterSwap', function(evt) {
    initCharts();
});
</script>
{% endblock script %}